language: csharp
mono: none
dotnet: 5.0.100
branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
script:
  - ls -l
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - dotnet pack -c release
